import { StyleSheet } from 'react-native';

export const profilestyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    padding: 20,
  },
  loadingContainer: {
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#614C3E',
    fontSize: 16,
  },
  imageContainer: {
    marginBottom: 20,
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: '#E6D5C9',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  editIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#8A7D6D',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#F7E6CA',
  },
  sectionTitle: {
    alignSelf: 'flex-start',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#614C3E',
    marginBottom: 10,
    marginLeft: 20,
  },
  input: {
    width: '90%',
    backgroundColor: '#FFFFFF',
    padding: 12,
    marginVertical: 10,
    borderRadius: 10,
    shadowColor: '#8A7D6D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    fontSize: 16,
  },
  hint: {
    color: '#8A7D6D',
    fontSize: 12,
    alignSelf: 'flex-start',
    marginLeft: 25,
    marginTop: -5,
    fontStyle: 'italic',
  },
  saveButton: {
    backgroundColor: '#D9BBB1',
    borderRadius: 10,
    paddingHorizontal: 30,
    paddingVertical: 12,
    marginTop: 20,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
